version: "3"
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mysecretpassword

  express-app:
    build:
      context: teebay_be
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://myuser:mysecretpassword@postgres:5432/mydb
      PORT: 4000
      JWT_SECRET: mysecret123

  frontend:
    build:
      context: teebay
      args:
        - VITE_BASE_URL=http://localhost:4000
    ports:
      - "8080:8080"
    depends_on:
      - express-app
    environment:
      VITE_BASE_URL: http://localhost:4000

volumes:
  postgres-data:
